uurloon = input('Wat verdien je per uur? ')
aantaluur = input('Hoeveel uur heb je gewerkt? ')
print(uurloon)
print(aantaluur)
print(str(aantaluur) + ' uur werken levert ' + str((float(uurloon) * float(aantaluur))) + ' euro op!')